FROM owncloud/ubuntu:16.04@sha256:f82f28705d54e6b42e680156a164f75ad18aa908e5e90c353a7fb0b53fdde7b7

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Antora"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/antora"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/antora"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/antora"

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["antora"]

RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
    echo "deb https://deb.nodesource.com/node_8.x xenial main" | tee /etc/apt/sources.list.d/node.list

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y nodejs git-core && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    npm install -g yarn npx --force

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y tree build-essential python libssl-dev && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN yarn global add @antora/cli @antora/site-generator-default

COPY rootfs /
